version: '3.8'
services:
  db:
    image: postgres:15
    container_name: sentinel-iam-db
    restart: always
    environment:
      POSTGRES_USER: sentinel
      POSTGRES_PASSWORD: sentinel_pass
      POSTGRES_DB: sentinel_iam
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: sentinel-iam-app
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sentinel_iam
      SPRING_DATASOURCE_USERNAME: sentinel
      SPRING_DATASOURCE_PASSWORD: sentinel_pass
      SERVER_PORT: 8080
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  postgres_data:
